JobEasywithGOC/Controllers/ApplicantController.cs
using JobEasyWithGOC.Data;
using JobEasyWithGOC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using GoC.WebTemplate.Components.Core.Services;
using JobEasyWithGOC.Data.Interfaces;
using AutoMapper;
using JobEasyWithGOC.Data.DataModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace JobEasyWithGOC.Controllers
{
    public class ApplicantController : ExtendedBaseController
    {
        private readonly ApplicationDbContext _db;
        private readonly IApplicantRepository _ApplicantRepository;
        private readonly    IMapper _mapper;
        public ApplicantController(ApplicationDbContext db, ModelAccessor modelAccessor, IMapper mapper, IApplicantRepository ApplicantRepository) : base(modelAccessor)
        {
            _db = db;
            _ApplicantRepository = ApplicantRepository;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            IEnumerable<ApplicantViewModel> objApplicantList  = _mapper.Map<List<ApplicantViewModel>>(_db.Applicants.ToList());
            

            return View(objApplicantList);
        }

        //GET
        public IActionResult Create()
        {

            var applicant = new ApplicantViewModel();
            applicant.Countrylist = _mapper.Map<List<CountryViewModel>>(_db.Countries).Select(dc => new SelectListItem { Text = dc.Name, Value = dc.Id.ToString()}).ToList();
            applicant.Provincelist = _mapper.Map<List<ProvinceViewModel>>(_db.Provinces).Select(dc => new SelectListItem{ Text = dc.Name, Value = dc.Id.ToString() }).ToList();
            return View(applicant);
            }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicantViewModel obj)
        {

            if (ModelState.IsValid)
            {
                var Applicant = _mapper.Map<Applicant>(obj);
                foreach (var c in _db.Countries.ToList())
                {
                    if (c.Name == Applicant.Country.Name)
                    {
                        Applicant.Country = c;
                    }
                }
                foreach (var p in _db.Provinces.ToList())
                {
                    if (p.Name == Applicant.Province.Name)
                    {
                        Applicant.Province = p;
                    }
                }


                _ApplicantRepository.RegisterAsync(Applicant);
                TempData["success"] = "Applicant created successfully.";
                return RedirectToAction("Index");
            }
            obj.Countrylist = _db.Countries.Select(dc => new SelectListItem { Text = dc.Name, Value = dc.Name}).ToList();
            obj.Provincelist = _db.Provinces.Select(dc => new SelectListItem { Text = dc.Name, Value = dc.Name }).ToList();
            return View(obj);
        }

        
        //GET
        public IActionResult Edit(string id)
        {   
            
            if (id == null)
            {
                return NotFound();
            }
            var ApplicantformDb = _ApplicantRepository.GetApplicantAsync(Int16.Parse(id));
            if (ApplicantformDb == null)
            {
                return NotFound();
            }
            var Applicant = _mapper.Map<ApplicantViewModel>(ApplicantformDb.Result);
            Applicant.Countrylist = _mapper.Map<List<CountryViewModel>>(_db.Countries).Select(dc => new SelectListItem { Text = dc.Name, Value = dc.Name }).ToList();
            Applicant.Provincelist = _mapper.Map<List<ProvinceViewModel>>(_db.Provinces).Select(dc => new SelectListItem { Text = dc.Name, Value = dc.Name }).ToList();

            return View(Applicant);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit
            (ApplicantViewModel obj)
        {
          
            if (ModelState.IsValid)
            {
                var Applicant =_ApplicantRepository.EditApplicantAsync(_mapper.Map<Applicant>(obj));
                TempData["success"] = "Applicant updated successfully.";

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Delete(string id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var ApplicantformDb = _ApplicantRepository.GetApplicantAsync(Int16.Parse(id));
            if (ApplicantformDb == null)
            {
                return NotFound();
            }
            var Applicant = _mapper.Map<ApplicantViewModel>(ApplicantformDb.Result);
            Applicant.Countrylist = _mapper.Map<List<CountryViewModel>>(_db.Countries).Select(dc => new SelectListItem { Text = dc.Name, Value = dc.Name }).ToList();
            Applicant.Provincelist = _mapper.Map<List<ProvinceViewModel>>(_db.Provinces).Select(dc => new SelectListItem { Text = dc.Name, Value = dc.Name }).ToList();

            return View(Applicant);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete
            (ApplicantViewModel obj)
        {

            if (ModelState.IsValid)
            {
                var Applicant = _ApplicantRepository.DeactivateApplicantAsync(_mapper.Map<Applicant>(obj).Id);
                TempData["success"] = "Applicant updated successfully.";

                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Detail(string id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var ApplicantformDb = _ApplicantRepository.GetApplicantAsync(Int16.Parse(id));
            if (ApplicantformDb == null)
            {
                return NotFound();
            }
            var Applicant = _mapper.Map<ApplicantViewModel>(ApplicantformDb.Result);

            return View(Applicant);
        }
        //GET
        public IActionResult Apply(string id)
        {

            
            var ApplicantformDb = _ApplicantRepository.GetApplicantAsync(Int16.Parse(id));
            if (ApplicantformDb == null)
            {
                return NotFound();
            }
            var Applicant = _mapper.Map<ApplicantViewModel>(ApplicantformDb.Result);
            Applicant.JobPostList = _mapper.Map<List<JobPostViewModel>>(_db.JobPosts.ToList());

            return View(Applicant);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Apply
            (ApplicantViewModel obj)
        {

            if (ModelState.IsValid)
            {
                var Applicant = _ApplicantRepository.DeactivateApplicantAsync(_mapper.Map<Applicant>(obj).Id);
                TempData["success"] = "Applicant updated successfully.";

                return RedirectToAction("Index");
            }
            return View(obj);
        }

    }

}

JobEasywithGOC/Controllers/CompanyController.cs
using JobEasyWithGOC.Data;
using JobEasyWithGOC.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using GoC.WebTemplate.Components.Core.Services;
using JobEasyWithGOC.Data.Interfaces;
using AutoMapper;
using JobEasyWithGOC.Data.DataModel;

namespace JobEasyWithGOC.Controllers
{
    public class CompanyController : ExtendedBaseController
    {
        private readonly ApplicationDbContext _db;
        private readonly ICompanyRepository _CompanyRepository;
        private readonly    IMapper _mapper;
        public CompanyController(ApplicationDbContext db, ModelAccessor modelAccessor, IMapper mapper, ICompanyRepository CompanyRepository) : base(modelAccessor)
        {
            _db = db;
            _CompanyRepository = CompanyRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            IEnumerable<CompanyViewModel> objCompanyList  = _mapper.Map<List<CompanyViewModel>>(_db.Companys.ToList());
            

            return View(objCompanyList);
        }

        //GET
        public IActionResult Create()
        {


            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CompanyViewModel obj)
        {
            
            if (ModelState.IsValid)
            {
                var company = _mapper.Map<Company>(obj);
                _CompanyRepository.RegisterAsync(company);
                TempData["success"] = "Company created successfully.";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        
        //GET
        public IActionResult Edit(string id)
        {   
            
            if (id == null)
            {
                return NotFound();
            }
            var CompanyformDb = _CompanyRepository.GetCompanyAsync(Int16.Parse(id));
            if (CompanyformDb == null)
            {
                return NotFound();
            }
            var Company = _mapper.Map<CompanyViewModel>(CompanyformDb.Result);

            return View(Company);
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit
            (CompanyViewModel obj)
        {
          
            if (ModelState.IsValid)
            {
                var Company =_CompanyRepository.EditCompanyAsync(_mapper.Map<Company>(obj));
                TempData["success"] = "Company updated successfully.";

                return RedirectToAction("Index");
            }
            return View(obj);
        }
        //GET
        public IActionResult Delete(string id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var CompanyformDb = _CompanyRepository.GetCompanyAsync(Int16.Parse(id));
            if (CompanyformDb == null)
            {
                return NotFound();
            }
            var Company = _mapper.Map<CompanyViewModel>(CompanyformDb.Result);

            return View(Company);
        }
        //POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(CompanyViewModel obj)
        {


            
                var Company = _CompanyRepository.DeactivateCompanyAsync(_mapper.Map<Company>(obj).Id);
                TempData["success"] = "Company updated successfully.";

                return RedirectToAction("Index");
          
        }


        public IActionResult Detail(string id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var CompanyformDb = _CompanyRepository.GetCompanyAsync(Int16.Parse(id));
            if (CompanyformDb == null)
            {
                return NotFound();
            }
            var Company = _mapper.Map<CompanyViewModel>(CompanyformDb.Result);

            return View(Company);
        }

    }
}

JobEasywithGOC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!--[if lt IE 9]><html class="no-js lt-ie9" lang="en" dir="ltr"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="en" dir="ltr"><!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW) wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html -->
		<title>Samples - home</title>
		<meta content="width=device-width,initial-scale=1" name="viewport">
		<!-- Meta data -->
		<meta name="description" content="Web Experience Toolkit (WET) includes reusable components for building and maintaining innovative Web sites that are accessible, usable, and interoperable. These reusable components are open source software and free for use by departments and external Web communities">
		<!-- Meta data-->
		<!-- Load closure template scripts -->
		<!--
			Note: a relative path is being used in this sample. In order to incorporate the script tags in your code, use the following absolute path (depending on the choice of domain).
			This path can be used for the following three file names: soyutils.js, wet-en.js, and wet-fr.js.
			canada.ca: https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/[file name]
			cdts.service.canada.ca: https://cdts.service.canada.ca/app/cls/WET/gcweb/v4_0_44/cdts/compiled/[file name]
			templates.service.gc.ca: https://templates.service.gc.ca/app/cls/WET/gcweb/v4_0_44/cdts/compiled/[file name]
			To point to the run version:
			canada.ca: https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/compiled/[file name]
			cdts.service.canada.ca: https://cdts.service.canada.ca/rn/cls/WET/gcweb/cdts/compiled/[file name]
			templates.service.gc.ca: https://templates.service.gc.ca/rn/cls/WET/gcweb/cdts/compiled/[file name]
		-->
		<script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/soyutils.js"></script>
		<script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/wet-en.js"></script>
		<noscript>
			<!-- Write closure fall-back static file -->
			<!-- refTop.html -->
		</noscript>
		<!-- Write closure template -->
		<script>
			document.write(wet.builder.refTop({
				"cdnEnv": "esdcprod"
			}));
		</script>
	</head>
	<body vocab="https://schema.org/" typeof="WebPage">
		<div id="def-top">
			<!-- Write closure fall-back static file -->
			<!-- top-en.html -->
		</div>
		<!-- Write closure template -->
		<script>
			var defTop = document.getElementById("def-top");
			defTop.outerHTML = wet.builder.top({
				"lngLinks": [{
					"lang": "fr",
					"href": "?lang=fr",
					"text": "Français"
				}],
				"breadcrumbs": [{
					"title": "Canada.ca",
					"acronym": "Canada.ca",
					"href": "https://www.canada.ca/en.html"
				}, {
					"title": "CDTS",
					"acronym": "Centrally Deployed Templates Solution",
					"href": "https://github.com/wet-boew/cdts-sgdc/blob/ec829335ba0d1019469dee998566a56a907986f0/public/gcweb/samples/index.html"
				},{
					"title": "Job",
					"acronym": "JobPost"
				
				}],
				"cdnEnv": "esdcprod"
			});
		</script>
		<main property="mainContentOfPage" typeof="WebPageElement" class="container">
			@RenderBody()
			@await RenderSectionAsync("Scripts", required: false)
            <div id="def-preFooter">
				<!-- Write closure fall-back static file -->
				<!-- preFooter-en.html -->
			</div>
			<!-- Write closure template -->
			<script>
				var defPreFooter = document.getElementById("def-preFooter");
				defPreFooter.outerHTML = wet.builder.preFooter({
					"dateModified": "2021-05-25",
					"cdnEnv": "esdcprod"
				});
			</script>
		</main>
		<div id="def-footer">
			<!-- Write closure fall-back static file -->
			<!-- footer-en.html -->
		</div>
		<!-- Write closure template -->
		<script>
			var defFooter = document.getElementById("def-footer");
			defFooter.outerHTML = wet.builder.footer({
				"cdnEnv": "esdcprod"
			});
		</script>
		<!-- Write closure template -->
		<script>
			document.write(wet.builder.refFooter({
				"cdnEnv": "esdcprod"
			}));
		</script>
		
	</body>
</html>

JobEasywithGOC/Views/Shared/_Layoutfr.cshtml
<!DOCTYPE html>
<!--[if lt IE 9]><html class="no-js lt-ie9" lang="en" dir="ltr"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="fr" dir="ltr"><!--<![endif]-->
	<head>
		<meta charset="utf-8">
		<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW) wet-boew.github.io/wet-boew/License-en.html / wet-boew.github.io/wet-boew/Licence-fr.html -->
		<title>Samples - home</title>
		<meta content="width=device-width,initial-scale=1" name="viewport">
		<!-- Meta data -->
		<meta name="description" content="Web Experience Toolkit (WET) includes reusable components for building and maintaining innovative Web sites that are accessible, usable, and interoperable. These reusable components are open source software and free for use by departments and external Web communities">
		<!-- Meta data-->
		<!-- Load closure template scripts -->
		<!--
			Note: a relative path is being used in this sample. In order to incorporate the script tags in your code, use the following absolute path (depending on the choice of domain).
			This path can be used for the following three file names: soyutils.js, wet-en.js, and wet-fr.js.
			canada.ca: https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/[file name]
			cdts.service.canada.ca: https://cdts.service.canada.ca/app/cls/WET/gcweb/v4_0_44/cdts/compiled/[file name]
			templates.service.gc.ca: https://templates.service.gc.ca/app/cls/WET/gcweb/v4_0_44/cdts/compiled/[file name]
			To point to the run version:
			canada.ca: https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/compiled/[file name]
			cdts.service.canada.ca: https://cdts.service.canada.ca/rn/cls/WET/gcweb/cdts/compiled/[file name]
			templates.service.gc.ca: https://templates.service.gc.ca/rn/cls/WET/gcweb/cdts/compiled/[file name]
		-->
		<script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/soyutils.js"></script>
		<script type="text/javascript" src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_43/cdts/compiled/wet-en.js"></script>
		<noscript>
			<!-- Write closure fall-back static file -->
			<!-- refTop.html -->
		</noscript>
		<!-- Write closure template -->
		<script>
			document.write(wet.builder.refTop({
				"cdnEnv": "esdcprod"
			}));
		</script>
	</head>
	<body vocab="https://schema.org/" typeof="WebPage">
		<div id="def-top">
			<!-- Write closure fall-back static file -->
			<!-- top-en.html -->
		</div>
		<!-- Write closure template -->
		<script>
			var defTop = document.getElementById("def-top");
			defTop.outerHTML = wet.builder.top({
				"lngLinks": [{
					"lang": "en",
					"href": "?lang=en",
					"text": "English"
				}],
				"breadcrumbs": [{
					"title": "Canada.ca",
					"acronym": "Canada.ca",
					"href": "https://www.canada.ca/en.html"
				}, {
					"title": "CDTS",
					"acronym": "Centrally Deployed Templates Solution",
					"href": "https://github.com/wet-boew/cdts-sgdc/blob/ec829335ba0d1019469dee998566a56a907986f0/public/gcweb/samples/index.html"
				},{
					"title": "Employer",
					"acronym": "Employer"
				}],
				"cdnEnv": "esdcprod"
			});
		</script>
		<main property="mainContentOfPage" typeof="WebPageElement" class="container">
			@RenderBody()
			@await RenderSectionAsync("Scripts", required: false)
            <div id="def-preFooter">
				<!-- Write closure fall-back static file -->
				<!-- preFooter-en.html -->
			</div>
			<!-- Write closure template -->
			<script>
				var defPreFooter = document.getElementById("def-preFooter");
				defPreFooter.outerHTML = wet.builder.preFooter({
					"dateModified": "2021-05-25",
					"cdnEnv": "esdcprod"
				});
			</script>
		</main>
		<div id="def-footer">
			<!-- Write closure fall-back static file -->
			<!-- footer-en.html -->
		</div>
		<!-- Write closure template -->
		<script>
			var defFooter = document.getElementById("def-footer");
			defFooter.outerHTML = wet.builder.footer({
				"cdnEnv": "esdcprod"
			});
		</script>
		<!-- Write closure template -->
		<script>
			document.write(wet.builder.refFooter({
				"cdnEnv": "esdcprod"
			}));
		</script>
		
	</body>
</html>

JobEasywithGOC/Views/Shared/_menu.cshtml
<div class="pnl-strt container visible-md visible-lg nvbar">
	<div class="row">
				<ul class="list-inline menu" id="lorm" role="menubar" >
					<li>
						<details>
							<summary>Menu</summary>
							<ul role="menu">
								<li><a asp-controller="Job" asp-action="Index">Job Post</a></li>
							</ul>
							<ul role="menu">
								<li><a asp-controller="Applicant" asp-action="Index" >Applicant</a></li>
							</ul>
							<ul role="menu">
								<li><a asp-controller="Company" asp-action="Index" >Company</a></li>
							</ul>
							<ul role="menu">
								<li><a asp-controller="Application" asp-action="Index" >Application</a></li>
							</ul>
						</details>
					</li>
				</ul>			
	</div>	
	</div>